from . import product_product
from . import sale_order_line
from . import sale_order
from . import res_config_settings
from . import product_template
from . import product_pricelist
from . import product_pricelist_item
from . import stock_move
from . import stock_picking
from . import stock_move_line
from . import product_product
from . import mrp_production
from . import city_distance
from . import delivery_carrier
from . import sale_commission
from . import res_partner
from . import calculation
from . import purchase_order
from . import purchase_order_line
from . import stock_quant
